-- Script para associar vagas a um recrutador
-- Execute no SQL Editor do Supabase (supabase.com/dashboard > SQL Editor)
--
-- 1. Cadastre um novo recrutador no app (signup)
-- 2. Obtenha o ID do recrutador:
--    - Supabase Dashboard > Authentication > Users > clique no usuário > copie o "User UID"
--
-- Opção A: Atribuir UMA vaga específica ao recrutador
-- UPDATE "Job"
-- SET user_id = 'ID_DO_RECRUTADOR'
-- WHERE id = 'ID_DA_VAGA';
--
-- Opção B: Atribuir TODAS as vagas (sem dono) ao recrutador
-- UPDATE "Job"
-- SET user_id = 'ID_DO_RECRUTADOR'
-- WHERE user_id IS NULL;
